### ISSUE TITLE
请问全拼可以用辅助码吗？

### ISSUE THREAD

**Issue by Konfido** [functoreality/rime-flypy-zrmfast#1]
自己因为拼音打字的重码问题烦躁了很久，想使用辅码，但又实在不想再重新去学双拼...
请问有可能在全拼时使用辅码吗？形码，笔画都可以
如果可能的话，要怎么实现吗？（目前粗浅猜测：需要在全拼dict中每个单字的条目后加上对应的形码，然后再把新词典引入到translator/dictionary或者import_tables中？）

麻烦大佬指教~

**Comment by functoreality** [comment]
最新版本已添加全拼下启用辅助码的选项；实现方式是用拼写运算把小鹤双拼翻译成全拼。

**Comment by Konfido** [comment]
赞！！感恩！已经用上了~

**Comment by Konfido** [comment]
然后有个小问题：输入中文的时候，列表里总会有些奇怪的词汇跟一个阴阳的符号，或者像是显示错误的问号，比如这样：

<img width="332" alt="image" src="https://user-images.githubusercontent.com/25447610/176942503-14b1ee70-9c44-430d-bae6-4c059ff69983.png">


<img width="197" alt="image" src="https://user-images.githubusercontent.com/25447610/176942381-9d8a7a90-8e4f-4b2a-96ed-a401c44e9844.png">

**Comment by functoreality** [comment]
> 然后有个小问题：输入中文的时候，列表里总会有些奇怪的词汇跟一个阴阳的符号，或者像是显示错误的问号，比如这样：
> 
> <img alt="image" width="332" src="https://user-images.githubusercontent.com/25447610/176942503-14b1ee70-9c44-430d-bae6-4c059ff69983.png">
> 
> <img alt="image" width="197" src="https://user-images.githubusercontent.com/25447610/176942381-9d8a7a90-8e4f-4b2a-96ed-a401c44e9844.png">

现已关闭 ☯。目前还存在的问题是一些（没有形码的）生僻字会跑到候选项的前面，有的甚至生僻到系统字体没有收录，这种情况下就可能显示为方框、问号等。相应的解决方案还需要探索。

**Comment by Konfido** [comment]
感謝修復！很好用！

ps. 也許可以把default.custom中得小鶴雙拼註釋掉，repo裏沒有這個配置，會導致部署時報錯
