### ISSUE TITLE
部分情况下无法开启辅助码

### ISSUE THREAD

**Issue by lovelock** [functoreality/rime-flypy-zrmfast#10]
感谢老哥的无私奉献，目前你这套配置是我用着最顺手的（小鹤双拼+鹤形辅助码+直接引导辅助码）。

文档里也说明了有这种情况，不过我还是希望知道为什么有些情况下无法tab，举个例子
几波
<img width="331" alt="image" src="https://user-images.githubusercontent.com/2208731/212816063-b9b30b42-2897-4df9-8e4e-0845fc873d53.png">

这时候按“Tab”完全不起作用。

之前我一直在找这种方案，最开始找到的是搜狗输入法+自定义词组，不过由于隐私问题还要配合一个lulu感觉很麻烦，别人也都说rime框架实现不了这种功能，我很想了解一下你是怎么实现的，也许我也可以帮忙完善这个项目。

**Comment by functoreality** [comment]
有点没理解你说的是个什么情况？设置的是“直接引导辅助码”，还是“tab引导辅助码”？如果是前者的话，“几波”的输入码可以是 `jibod`，后者的话是 `jibo<Tab>d`。
如果你指的是 双拼加形输入 的实现方式的话，我没有直接用 Rime 自带的拼音字典文件，而是专门制作了新的字典，把辅助码直接写进各个字的编码里。然后设置拼写运算（见 `flypy_zrmfast.schema.yaml` 里的 `speller/algebra:`），以允许不带辅助码的纯双拼输入，和 Rime 自带的朙月拼音（全拼）里允许不带韵母输入的方式差不多。

**Comment by lovelock** [comment]
我理解直接引导辅助码省略的是[，而tab是用来定位置的，上面我的需求是按tab能实现ji|bo，然后按p定位到几，再按d定位到波

**Comment by lovelock** [comment]
我试了下确实是这样，按下d就可以按tab了

**Comment by functoreality** [comment]
这个应该是直接引导辅助码所带来的断字歧义问题。Tab 一次应该是移动一个字，这需要先将输入码按字划分。而 `jibo` 刚好对应一个完整的字，所以 Tab 一次后就并没有进行移动。
一种解决方法是先追加最后一个字的辅助码，比如加了 d 后 Rime 就会重新断字，这个时候 Tab 能够发挥作用。
另一种办法是先按方向键 下（或者等价的 Control+n），让 Rime 聚焦到第二候选，这时候“激波”对应的是输入码断成两个字，之后 Tab 能够进行移动。
（不开启直接引导辅助码的话，就不会遇到这种问题。）

**Comment by lovelock** [comment]
确实是，不过我感觉开启直接引导辅助码才是这套配置的精髓所在，不然打字过程一直要按[还是挺奇怪的。

irime输入法群里这个老哥的配置使用了大量词库，https://github.com/iDvel/rime-ice，我觉得也不错，不过就是没有你的这个功能强大。

我猜其实你们都保留了处理词库的代码没有提交，你的应该是从原始什么词库（相对较小）生成flypy_zrmfast.schema.yaml，他的是从搜狗、腾讯（大词库，毕竟他的是纯双拼方案）等生成。

如果让你这个配置加上他的词库，必将是一套完美的配置。

另外提一个小问题，你的这个配置中文半角环境下，输入 @ 需要选符号，这和常用的聊天工具中 at 人的操作冲突了，选了符号之后系统提示就没了，所以我fork了下你的配置加了这个
<img width="904" alt="image" src="https://user-images.githubusercontent.com/2208731/213069030-0771fc26-bf4f-4299-8bad-868ec864938b.png">
