### ISSUE TITLE
最新版本Squirrel tab无法引导辅助码

### ISSUE THREAD

**Issue by lovelock** [functoreality/rime-flypy-zrmfast#12]
关联一下这个问题 https://github.com/functoreality/rime-flypy-zrmfast/issues/10

前天更新了最新版本之后发现输入词想要给第一个字加辅助码（之前是按Tab）时会变成选字模式，比如输入“辅助码” `fuvuma`
预期是
<img width="369" alt="image" src="https://user-images.githubusercontent.com/2208731/216501139-7a77700b-b34b-45a9-ab46-324fbec01307.png">
但实际是
<img width="362" alt="image" src="https://user-images.githubusercontent.com/2208731/216501175-eb094edb-3b79-4473-84f0-c8c3b76cdf3a.png">

不过我试了下Emacs的光标移动方法Ctrl+AEBF是可以用的，Ctrl+A/E分别是最前和最后，Ctrl+F是往后移动一个字母，但Ctrl+B的行为有些不同，是移动一个字，还以辅助码为例，按Ctrl+B的效果是这样的
<img width="369" alt="image" src="https://user-images.githubusercontent.com/2208731/216501937-82e072f6-4e5f-4995-84a3-0ef021a4c6e3.png">

**Comment by functoreality** [comment]
或许可以检查一下→方向键（或 Ctrl+F）的功能，直接在光标位于输入码末尾的时候按？原来的默认行为应该是移动光标到开头，按↓才是移动到第二候选，这种设定对追加辅助码的功能还是挺重要的。
我以前在安卓 Trime 遇到过类似的问题，那里因为候选项默认横向排列，所以按→的默认行为变成了移动到第二候选，不过这个问题可以通过一些配置项改回来。
如果鼠须管的新版本也是这个问题的话，可能需要再去读一下文档（虽然我看到文档更新了，但没找到相应的选项在哪…），看怎么把方向键的默认行为改一下。

**Comment by lovelock** [comment]
已经确认是升级引起的，最新版本已经修复了。

<img width="857" alt="image" src="https://user-images.githubusercontent.com/2208731/217140060-87d36eec-8c04-492f-a15b-4996d7108b4a.png">
