### ISSUE TITLE
用afd输入日期的时候, 无法用次选键和数字来选择候选项上屏

### ISSUE THREAD

**Issue by salonz** [functoreality/rime-flypy-zrmfast#13]
反而数字小键盘上的数字键倒是可以选择, 不知道是否可以修复

**Comment by functoreality** [comment]
新提交了一个版本，可以看看有没有解决？
之前出现这个问题的原因应该是 Rime 把数字、分号这些字符都当作了 lua_translator 的输入，而没有按照普通的上屏键处理。目前的解决方案是让 lua_translator 自己承担上屏判断的功能。

**Comment by salonz** [comment]
> 新提交了一个版本，可以看看有没有解决？ 之前出现这个问题的原因应该是 Rime 把数字、分号这些字符都当作了 lua_translator 的输入，而没有按照普通的上屏键处理。目前的解决方案是让 lua_translator 自己承担上屏判断的功能。

可以了, 感谢.
