### ISSUE TITLE
辅助码提示问题 

### ISSUE THREAD

**Issue by iNyanPasu** [functoreality/rime-flypy-zrmfast#17]
![Snipaste_2024-01-06_09-28-00](https://github.com/functoreality/rime-flypy-zrmfast/assets/75481306/8872fefb-f47c-4a35-a1ee-8e14ac65607e)
![Snipaste_2024-01-06_09-21-41](https://github.com/functoreality/rime-flypy-zrmfast/assets/75481306/78ccd1ea-f6bc-4be6-a562-0e4802c2f214)
![Snipaste_2024-01-06_09-24-25](https://github.com/functoreality/rime-flypy-zrmfast/assets/75481306/9006cd9d-5817-4049-a9cc-90225cdb0090)
能否实现 "助"和"码‘都有辅助码提示？

**Comment by functoreality** [comment]
在 `flypy_zrmfast.custom.yaml` 里找到这一行（可以在文件内搜索）：
```yaml
#translator/spelling_hints: 0 ## 关闭单字编码提示
```
删掉最前面的井号，并且把后面的 0 改成大一些的数就行。比如如果设成 3 的话，不超过 3 个字的候选项会显示所有字的辅助码，超过 4 个字的候选就不显示了（考虑到太长的提示可能造成干扰）。你可以根据自己的需要设一个数。

**Comment by iNyanPasu** [comment]
flypy_flypy.dict.yaml 中我不太懂，像
```
ㄓ	vi[[
ㄔ	ii[[
ㄕ	ui[[
```
这样的是不是无法打出来？我不知道 `vi[[`啥意思

**Comment by functoreality** [comment]
> flypy_flypy.dict.yaml 中我不太懂，像
> 
> ```
> ㄓ	vi[[
> ㄔ	ii[[
> ㄕ	ui[[
> ```
> 
> 这样的是不是无法打出来？我不知道 `vi[[`啥意思

就是表示“㞢”的读音是 zhi（小鹤双拼是 vi），这个字没有形码，所以辅助码部分是 `[[`。本来敲 `vi[[` 应该是能打出来这个字的，不过可能因为这个字是注音符号而不是普通汉字，我推测它触发了 Rime 的过滤机制，把它从候选项里删掉了，所以用一般的方式打不出来。

**Comment by yxldl101** [comment]
请问这个英文模式，能否实现打单词的时候自动补全空格

**Comment by functoreality** [comment]
> 请问这个英文模式，能否实现打单词的时候自动补全空格

目前是没有的。毕竟主方案还是中文输入，`aw` 这个前缀只是用来偶尔插入一两个单词，连续输入单词的机会不多，所以在我的理解里面这个功能好像不是特别必要？
如果需要连续输入英文单词的话，可以考虑直接用 [easy-en](https://github.com/BlindingDark/rime-easy-en) 项目，那里面有自动补全空格的功能。
