### ISSUE TITLE
关于flypy_zrmfast.dict.yaml词库中，同字多码问题请教

### ISSUE THREAD

**Issue by kingdream123** [functoreality/rime-flypy-zrmfast#3]
大佬在 flypy_zrmfast.dict.yaml 词库中同一个字有多个输入码，而且这个字也不是多音字。这个对应多个的作用是啥呀
例如：
京	jk[wk	100%
京	yr[wk	0%
副	fu[hd	100%
副	pi[hd	0%
亲	qb[la	0%
亲	qk[la	0%
亲	xb[la	10%
亲	vf[la	90%

**Comment by functoreality** [comment]
这东西是 Rime 自带的 `luna_pinyin.dict.yaml` 里就有的，转换生成的新码表也就保留下来了，我自己也不清楚这里面的原因。猜测可能有的字在古代是多音字，近代白话文加简化字以后有的读音就几乎不用了，而 Rime 重视对古文字的支持，留下了这部分曾经有用的读音。

**Comment by kingdream123** [comment]
了解了，感谢~
